### ISSUE TITLE
Getting error on tmp file

### ISSUE THREAD

**Issue by fxfactorial** [hlissner/emacs-mips-mode#10]
Getting an error on tmp file like so (after trying to eval the buffer): 
<img width="567" alt="Screen Shot 2019-03-20 at 5 20 33 PM" src="https://user-images.githubusercontent.com/3036816/54727372-aaf3d580-4b34-11e9-9751-92191044f1d6.png">

then looks like because of that error, it gets caught in the help buffer as you can see in the mode line. 

GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-30

**Comment by hlissner** [comment]
Did you figure out a fix for this?

**Comment by fxfactorial** [comment]
Nope , closed because don’t care anymore
